title: Philip Lebo
email: philip.lebo+s@gmail.com
description: About Philip Lebo
url: "http://philiplebo.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
