title: Philip Lebo
email: philip@philiplebo.com
description: About Philip Lebo
url: "https://philiplebo.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
